//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugin.PEImageView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plugin.PEImageView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileSave {
            get {
                object obj = ResourceManager.GetObject("FileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconOpen {
            get {
                object obj = ResourceManager.GetObject("iconOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconOpenFile {
            get {
                object obj = ResourceManager.GetObject("iconOpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconOpenGAC {
            get {
                object obj = ResourceManager.GetObject("iconOpenGAC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconOpenProcess {
            get {
                object obj = ResourceManager.GetObject("iconOpenProcess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iconPe {
            get {
                object obj = ResourceManager.GetObject("iconPe", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NULL&gt;.
        /// </summary>
        internal static string NullString {
            get {
                return ResourceManager.GetString("NullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        internal static string Section_DIRECTORY_ARCHITECTURE {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_ARCHITECTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound Import.
        /// </summary>
        internal static string Section_DIRECTORY_BOUND_IMPORT {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_BOUND_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR Runtime Header.
        /// </summary>
        internal static string Section_DIRECTORY_COM_DECRIPTOR {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_COM_DECRIPTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Manager Table.
        /// </summary>
        internal static string Section_DIRECTORY_COR_CMT {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_COR_CMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Address Table.
        /// </summary>
        internal static string Section_DIRECTORY_COR_EAT {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_COR_EAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR Runtime Header.
        /// </summary>
        internal static string Section_DIRECTORY_COR_METADATA {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_COR_METADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Native Header.
        /// </summary>
        internal static string Section_DIRECTORY_COR_MNH {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_COR_MNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Table.
        /// </summary>
        internal static string Section_DIRECTORY_COR_RESOURCE {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_COR_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Name Singnature.
        /// </summary>
        internal static string Section_DIRECTORY_COR_SN {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_COR_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTable fixup.
        /// </summary>
        internal static string Section_DIRECTORY_COR_VTABLE {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_COR_VTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Section_DIRECTORY_DEBUG {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Import Descriptor.
        /// </summary>
        internal static string Section_DIRECTORY_DELAY_IMPORT {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_DELAY_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Table.
        /// </summary>
        internal static string Section_DIRECTORY_EXCEPTION {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Table.
        /// </summary>
        internal static string Section_DIRECTORY_EXPORT {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Ptr.
        /// </summary>
        internal static string Section_DIRECTORY_GLOBALPTR {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_GLOBALPTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAT.
        /// </summary>
        internal static string Section_DIRECTORY_IAT {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_IAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Table.
        /// </summary>
        internal static string Section_DIRECTORY_IMPORT {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Config Table.
        /// </summary>
        internal static string Section_DIRECTORY_LOAD_CONFIG {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_LOAD_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Relocation Table.
        /// </summary>
        internal static string Section_DIRECTORY_RELOCATION {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_RELOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Table.
        /// </summary>
        internal static string Section_DIRECTORY_RESOURCE {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Table.
        /// </summary>
        internal static string Section_DIRECTORY_SECURITY {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS Table.
        /// </summary>
        internal static string Section_DIRECTORY_TLS {
            get {
                return ResourceManager.GetString("Section_DIRECTORY_TLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COFF header.
        /// </summary>
        internal static string Section_IMAGE_COFF_HEADER {
            get {
                return ResourceManager.GetString("Section_IMAGE_COFF_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOS header.
        /// </summary>
        internal static string Section_IMAGE_DOS_HEADER {
            get {
                return ResourceManager.GetString("Section_IMAGE_DOS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header.
        /// </summary>
        internal static string Section_IMAGE_FILE_HEADER {
            get {
                return ResourceManager.GetString("Section_IMAGE_FILE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT header.
        /// </summary>
        internal static string Section_IMAGE_NT_HEADERS {
            get {
                return ResourceManager.GetString("Section_IMAGE_NT_HEADERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional header.
        /// </summary>
        internal static string Section_IMAGE_OPTIONAL_HEADER {
            get {
                return ResourceManager.GetString("Section_IMAGE_OPTIONAL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string Section_IMAGE_SECTION {
            get {
                return ResourceManager.GetString("Section_IMAGE_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections header.
        /// </summary>
        internal static string Section_IMAGE_SECTION_HEADER {
            get {
                return ResourceManager.GetString("Section_IMAGE_SECTION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToolBar_Empty {
            get {
                object obj = ResourceManager.GetObject("ToolBar_Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single valid machine type compatible with the input type library must be specified..
        /// </summary>
        internal static string TypeLib_Err_BadMachineSwitch {
            get {
                return ResourceManager.GetString("TypeLib_Err_BadMachineSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly for referenced type library, &apos;{0}&apos;, will not be imported since it would overwrite existing file &apos;{1}&apos;..
        /// </summary>
        internal static string TypeLib_Err_ExistingFileOverwrittenByRefAsmArg2 {
            get {
                return ResourceManager.GetString("TypeLib_Err_ExistingFileOverwrittenByRefAsmArg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced assembly &apos;{0}&apos; is not a primary interop assembly..
        /// </summary>
        internal static string TypeLib_Err_ReferencedPIANotPIAArg1 {
            get {
                return ResourceManager.GetString("TypeLib_Err_ReferencedPIANotPIAArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; which is registered as the primary interop assembly for type library &apos;{1}&apos; is not actually a primary interop assembly..
        /// </summary>
        internal static string TypeLib_Err_RegisteredPIANotPIAArg2 {
            get {
                return ResourceManager.GetString("TypeLib_Err_RegisteredPIANotPIAArg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference lookup for a type library failed because the assembly &apos;{0}&apos; with TypeLib GUID &apos;{1}&apos; and version &apos;{2}.{3}&apos; does not match the type library &apos;{4}&apos; with TypeLib GUID &apos;{5}&apos; and version &apos;{6}.{7}&apos;..
        /// </summary>
        internal static string TypeLib_Msg_AsmRefLookupMatchProblemArg8 {
            get {
                return ResourceManager.GetString("TypeLib_Msg_AsmRefLookupMatchProblemArg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; loaded..
        /// </summary>
        internal static string TypeLib_Msg_AssemblyLoadedArg1 {
            get {
                return ResourceManager.GetString("TypeLib_Msg_AssemblyLoadedArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; resolved..
        /// </summary>
        internal static string TypeLib_Msg_AssemblyResolvedArg1 {
            get {
                return ResourceManager.GetString("TypeLib_Msg_AssemblyResolvedArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to type library &apos;{0}&apos; has been resolved to user specified assembly &apos;{1}&apos;..
        /// </summary>
        internal static string TypeLib_Msg_RefFoundInAsmRefListArg2 {
            get {
                return ResourceManager.GetString("TypeLib_Msg_RefFoundInAsmRefListArg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to type library &apos;{0}&apos; has been resolved to primary interop assembly &apos;{1}&apos;..
        /// </summary>
        internal static string TypeLib_Msg_ResolvedRefToPIAArg2 {
            get {
                return ResourceManager.GetString("TypeLib_Msg_ResolvedRefToPIAArg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving reference to type library &apos;{0}&apos;..
        /// </summary>
        internal static string TypeLib_Msg_ResolvingRefArg1 {
            get {
                return ResourceManager.GetString("TypeLib_Msg_ResolvingRefArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing a type library into a platform agnostic assembly.  This can cause errors if the type library is not truly platform agnostic..
        /// </summary>
        internal static string TypeLib_Wrn_AgnosticAssembly {
            get {
                return ResourceManager.GetString("TypeLib_Wrn_AgnosticAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced type library, &apos;{0}&apos;, contains a circular reference, and may not be fully imported..
        /// </summary>
        internal static string TypeLib_Wrn_CircularReferenceArg1 {
            get {
                return ResourceManager.GetString("TypeLib_Wrn_CircularReferenceArg1", resourceCulture);
            }
        }
    }
}
